In [3]:
import pandas as pd
# from sklearn.preprocessing import

In [4]:
df=pd.read_csv("titanic.csv")
df.drop(df[["PassengerId","Cabin","Pclass","Name","SibSp","Parch","Ticket",'Embarked']],axis='columns',inplace=True)

In [5]:
target=df.Survived
inputs=df.drop(['Survived'],axis='columns')

In [6]:
dummies=pd.get_dummies(df.Sex,dtype=int)

In [7]:
inputs=pd.concat([inputs,dummies],axis="columns",)

In [8]:
inputs.drop(["Sex"],axis="columns",inplace=True)

In [9]:
inputs.Age.fillna(inputs['Age'].median(),inplace=True)

C:\Users\gmadh\AppData\Local\Temp\ipykernel_17044\636130396.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  inputs.Age.fillna(inputs['Age'].median(),inplace=True)

In [10]:
inputs.head(10)

    Age     Fare  female  male
0  22.0   7.2500       0     1
1  38.0  71.2833       1     0
2  26.0   7.9250       1     0
3  35.0  53.1000       1     0
4  35.0   8.0500       0     1
5  28.0   8.4583       0     1
6  54.0  51.8625       0     1
7   2.0  21.0750       0     1
8  27.0  11.1333       1     0
9  14.0  30.0708       1     0

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(inputs,target,test_size=.3)

In [12]:
x_train

       Age      Fare  female  male
753  23.00    7.8958       0     1
49   18.00   17.8000       1     0
429  32.00    8.0500       0     1
353  25.00   17.8000       0     1
311  18.00  262.3750       1     0
..     ...       ...     ...   ...
233   5.00   31.3875       1     0
713  29.00    9.4833       0     1
762  20.00    7.2292       0     1
667  28.00    7.7750       0     1
831   0.83   18.7500       0     1

[623 rows x 4 columns]

In [13]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [14]:
model.fit(x_train,y_train)

GaussianNB()

In [15]:
model.score(x_test,y_test)

0.7798507462686567